server:
  port: 9000
spring:
  application:
    name: project12306-gateway${unique-name:}-service
  profiles:
#    active: aggregation
     active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.153.135:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
